2022-01-21 14:01:42,658 INFO    MainThread:2052 [wandb_setup.py:_flush():71] setting env: {}
2022-01-21 14:01:42,658 INFO    MainThread:2052 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-21 14:01:42,658 INFO    MainThread:2052 [wandb_init.py:_log_setup():371] Logging user logs to /Users/gdegournay/PycharmProjects/Udacity/MLOps/MLOps_ex/reproducible workflow/wandb/run-20220121_140142-32k25721/logs/debug.log
2022-01-21 14:01:42,658 INFO    MainThread:2052 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/gdegournay/PycharmProjects/Udacity/MLOps/MLOps_ex/reproducible workflow/wandb/run-20220121_140142-32k25721/logs/debug-internal.log
2022-01-21 14:01:42,658 INFO    MainThread:2052 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc43868d9a0>
2022-01-21 14:01:42,659 INFO    MainThread:2052 [wandb_init.py:init():404] calling init triggers
2022-01-21 14:01:42,659 INFO    MainThread:2052 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-21 14:01:42,659 INFO    MainThread:2052 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 2nfpd57w
2022-01-21 14:01:42,661 INFO    MainThread:2052 [wandb_run.py:finish():1457] finishing run geodego/demo_artifact/2nfpd57w
2022-01-21 14:01:42,661 INFO    MainThread:2052 [jupyter.py:save_history():429] not saving jupyter history
2022-01-21 14:01:42,662 INFO    MainThread:2052 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-21 14:01:42,662 INFO    MainThread:2052 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-21 14:01:42,663 INFO    MainThread:2052 [wandb_init.py:init():460] starting backend
2022-01-21 14:01:42,663 INFO    MainThread:2052 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-01-21 14:01:42,667 INFO    MainThread:2052 [backend.py:ensure_launched():216] starting backend process...
2022-01-21 14:01:42,670 INFO    MainThread:2052 [backend.py:ensure_launched():221] started backend process with pid: 2143
2022-01-21 14:01:42,676 INFO    MainThread:2052 [wandb_init.py:init():469] backend started and connected
2022-01-21 14:01:42,693 INFO    MainThread:2052 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-21 14:01:42,693 INFO    MainThread:2052 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-21 14:01:42,694 INFO    MainThread:2052 [wandb_init.py:init():533] updated telemetry
2022-01-21 14:01:42,695 INFO    MainThread:2052 [wandb_init.py:init():563] communicating current version
2022-01-21 14:01:43,532 INFO    MainThread:2052 [wandb_init.py:init():568] got version response 
2022-01-21 14:01:43,532 INFO    MainThread:2052 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-21 14:01:43,869 INFO    MainThread:2052 [wandb_init.py:init():606] starting run threads in backend
2022-01-21 14:01:45,472 INFO    MainThread:2052 [wandb_run.py:_console_start():1810] atexit reg
2022-01-21 14:01:45,472 INFO    MainThread:2052 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-21 14:01:45,472 INFO    MainThread:2052 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-21 14:01:45,473 INFO    MainThread:2052 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-21 14:01:45,473 INFO    MainThread:2052 [wandb_init.py:init():633] run started, returning control to user process
2022-01-21 14:02:02,197 INFO    MainThread:2052 [wandb_run.py:finish():1457] finishing run geodego/demo_artifact/32k25721
2022-01-21 14:02:02,198 INFO    MainThread:2052 [jupyter.py:save_history():429] not saving jupyter history
2022-01-21 14:02:02,198 INFO    MainThread:2052 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-21 14:02:02,199 INFO    MainThread:2052 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-21 14:04:24,731 INFO    MainThread:2052 [wandb_setup.py:_flush():71] setting env: {}
2022-01-21 14:04:24,732 INFO    MainThread:2052 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-21 14:04:24,732 INFO    MainThread:2052 [wandb_init.py:_log_setup():371] Logging user logs to /Users/gdegournay/PycharmProjects/Udacity/MLOps/MLOps_ex/reproducible workflow/wandb/run-20220121_140424-1uqmzsss/logs/debug.log
2022-01-21 14:04:24,732 INFO    MainThread:2052 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/gdegournay/PycharmProjects/Udacity/MLOps/MLOps_ex/reproducible workflow/wandb/run-20220121_140424-1uqmzsss/logs/debug-internal.log
2022-01-21 14:04:24,732 INFO    MainThread:2052 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc4505a84f0>
2022-01-21 14:04:24,732 INFO    MainThread:2052 [wandb_init.py:init():404] calling init triggers
2022-01-21 14:04:24,732 INFO    MainThread:2052 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-21 14:04:24,733 INFO    MainThread:2052 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 32k25721
2022-01-21 14:04:24,734 INFO    MainThread:2052 [wandb_run.py:finish():1457] finishing run geodego/demo_artifact/32k25721
2022-01-21 14:04:24,734 INFO    MainThread:2052 [jupyter.py:save_history():429] not saving jupyter history
2022-01-21 14:04:24,735 INFO    MainThread:2052 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-21 14:04:24,735 INFO    MainThread:2052 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-21 14:04:24,735 INFO    MainThread:2052 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-21 14:04:24,736 INFO    MainThread:2052 [wandb_run.py:_restore():1752] restore
2022-01-21 14:04:25,197 INFO    MainThread:2052 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 695
  total_bytes: 695
}

2022-01-21 14:04:30,305 INFO    MainThread:2052 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-01-21 14:04:30,408 INFO    MainThread:2052 [wandb_run.py:_restore():1752] restore
2022-01-21 14:04:30,420 ERROR   MainThread:2052 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1971, in _on_finish
    self._poll_exit_response = self._wait_for_finish()
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1911, in _wait_for_finish
    poll_exit_resp = self._backend.interface.communicate_poll_exit()
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 586, in communicate_poll_exit
    resp = self._communicate_poll_exit(poll_exit)
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 402, in _communicate_poll_exit
    result = self._communicate(rec)
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-21 14:04:47,328 INFO    MainThread:2052 [wandb_setup.py:_flush():71] setting env: {}
2022-01-21 14:04:47,328 INFO    MainThread:2052 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-21 14:04:47,329 INFO    MainThread:2052 [wandb_init.py:_log_setup():371] Logging user logs to /Users/gdegournay/PycharmProjects/Udacity/MLOps/MLOps_ex/reproducible workflow/wandb/run-20220121_140447-1qfyw6hj/logs/debug.log
2022-01-21 14:04:47,329 INFO    MainThread:2052 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/gdegournay/PycharmProjects/Udacity/MLOps/MLOps_ex/reproducible workflow/wandb/run-20220121_140447-1qfyw6hj/logs/debug-internal.log
2022-01-21 14:04:47,329 INFO    MainThread:2052 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc460c575e0>
2022-01-21 14:04:47,329 INFO    MainThread:2052 [wandb_init.py:init():404] calling init triggers
2022-01-21 14:04:47,329 INFO    MainThread:2052 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-21 14:04:47,330 INFO    MainThread:2052 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 32k25721
2022-01-21 14:04:47,331 INFO    MainThread:2052 [wandb_run.py:finish():1457] finishing run geodego/demo_artifact/32k25721
2022-01-21 14:04:47,331 INFO    MainThread:2052 [jupyter.py:save_history():429] not saving jupyter history
2022-01-21 14:04:47,332 INFO    MainThread:2052 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-21 14:04:47,332 INFO    MainThread:2052 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
